version: '2.1'

jobs:
  run-e2e-by-cli:
    docker:
      - image: selenium/node-chrome-debug
    steps:
      - run:
          name: Install nodejs and npm
          command: sudo apt install nodejs npm
      - run:
          name: Install mabl CLI
          command: sudo npm i -g @mablhq/mabl-cli@latest
      - run:
          name: mabl Auth
          command: mabl auth activate-key $MABL_API_KEY
      - run:
          name: check mabl Auth
          command: mabl auth info
      - run: mabl tests run --from-plan-id k6gNBmsMmM48DBE1gpoAUQ-p --headless

workflows:
  install-and-run-test:
    jobs:
      - run-e2e-by-cli

